### ISSUE TITLE
LineupURL fails if IP not defined

### ISSUE THREAD

**Issue by markcs** [markcs/HDHR_epg#4]
This line fails:
$lineUpURL = @$rdisc[0]->{LineupURL};

@$rdisc[0] returns these for me:
$VAR1 = {
          'DeviceID' => 'xxxx',
          'LocalIP' => '192.168.x.x',
          'Legacy' => 1,
          'BaseURL' => 'http://192.168.x.x',
          'DiscoverURL' => 'http://192.168.x.x/discover.json'
        };

**Comment by misullivan** [comment]
Oh, ok will catch that.. on mine it’s in rdisc.

**Comment by misullivan** [comment]
pushed a patch - try that now.

**Comment by markcs** [comment]
Fixed.
